### ISSUE TITLE
support heatmap?

### ISSUE THREAD

**Issue by AStupidBear** [ma-laforge/InspectDR.jl#3]

**Comment by ma-laforge** [comment]
Thanks for the interest.

At the moment, I am not planning on supporting heatmap.  Most of my work involves processing large datasets where y=f(x) - like time-domain simulation data.

InspectDR was built because I found most other backends were too slow/not interactive enough for my own needs.

Most of my (rare) heatmap needs are actually satisfied with other backends:  I don't need to display heatmap datasets that are particularly large - nor do I need to generate them that often.  In those cases, I would resort to PyPlot or something similar.

### Alternative
InspectDR.jl supports the `:shape` construct from Plots.jl, so it might be possible to implement a Plots.jl "recipe" to generate heatmaps on any backend that does not natively support them (including InspectDR)...

...The part I am unsure about is whether the recipe could successfully generate a legend...

**Comment by ma-laforge** [comment]
Just out of curiosity:  Why would you want heatmaps with InspectDR?

 - Do you like the speed of InspectDR?
 - Do you prefer how the output looks?
 - Do you prefer the mouse/keyboard interactivity?

Is there some other reason??

**Comment by AStupidBear** [comment]
Yes, I prefer the mouse/keyboard interactivity.

**Comment by ma-laforge** [comment]
Just added support for heatmaps on master branch.

See sample/demo14.jl for example.

Will be tagging a new release in the Julia registry soon.
